apiVersion: v1
kind: Pod
metadata:
  name: etcd-corruptor
  namespace: {{NAMESPACE}}
spec:
  containers:
  - name: corruptor
    image: alpine:latest
    command: ["sh", "-c", "mkdir -p /volume-1/member/snap /volume-2/member/snap && dd if=/dev/urandom of=/volume-1/member/snap/db bs=1024 count=100 && dd if=/dev/urandom of=/volume-2/member/snap/db bs=1024 count=100"]
    volumeMounts:
    - name: vol-1
      mountPath: /volume-1
    - name: vol-2
      mountPath: /volume-2
  restartPolicy: Never
  volumes:
  - name: vol-1
    persistentVolumeClaim:
      claimName: data-etcd-1
  - name: vol-2
    persistentVolumeClaim:
      claimName: data-etcd-2
